### ISSUE TITLE
fake deafen doesnt work?

### ISSUE THREAD

**Issue by whopastoo** [ItzOnlyAnimal/vencord-plugins#1]
nothing happens when you turn on the fake deafen option sadly

**Comment by nyakowint** [comment]
works on my machine!

**Comment by whopastoo** [comment]
> works on my machine!

is there a command or something i have to use to turn it on? because when i turn it on and deafen nothing happens

**Comment by whopastoo** [comment]
> works on my machine!

can i add you on discord so you can help me fix it? or maybe see if im have it setup right?
